name: 🚀 Feature Proposal
description: Propose a feature
title: "[🚀 Feature]: "
labels: [feature, triage]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to propose a feature!
  - type: textarea
    id: feature-description
    attributes:
      label: Feature and motivation
      description: |
        Describe clearly and concisely the feature you are proposing, what is the motivation
        behind it, and an example of how you would use the feature.
      placeholder: |
        Help us to understand your proposal by adding as many details as possible, we will look into
        it and give you feedback as soon as possible.
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Code of Conduct
      description: The Code of Conduct helps create a safe space for everyone. We require
        that everyone agrees to it.
      options:
        - label: I agree to follow this project's [Code of Conduct](https://opensource.saucelabs.com/sauce-togo/code-of-conduct)
          required: true
