name: 'Build Sauce To Go jars'
description: 'Build Sauce To Go jars'
runs:
  using: "composite"
  steps:
    - name: Build jars
      shell: bash
      run: |
        docker run --rm \
        -v ${PWD}:/usr/src/mymaven \
        -v ${PWD}/.m2:/root/.m2 \
        -w /usr/src/mymaven \
        maven:3.6.3-jdk-8 mvn clean package
