FROM openjdk:8-jre-slim

COPY sauce-assets-uploader-0.1-SNAPSHOT-jar-with-dependencies.jar /sauce-assets-uploader-0.1-SNAPSHOT.jar

RUN mkdir -p /opt/selenium/assets

CMD ["java", "-jar", "/sauce-assets-uploader-0.1-SNAPSHOT.jar"]
