FROM selenium/standalone-firefox:4.0.0-beta-1-prerelease-20201202

#==============================
# Sauce Labs logo as wallpaper for Fluxbox
#==============================
COPY saucelabs_logo_red_bolt.png /usr/share/images/fluxbox/ubuntu-light.png
