#== FROM instructions support variables that are declared by
# any ARG instructions that occur before the first FROM
# ref: https://docs.docker.com/engine/reference/builder/#understand-how-arg-and-from-interact
#
# To overwrite the build args use:
#  docker build ... --build-arg SELENIUM_TAG=4.0.0-beta-3-20210426
ARG SELENIUM_TAG=4.0.0-beta-3-20210426
FROM selenium/standalone-firefox:${SELENIUM_TAG}

#==============================
# Sauce Labs logo as wallpaper for Fluxbox
#==============================
COPY saucelabs_logo_red_bolt.png /usr/share/images/fluxbox/ubuntu-light.png
