FROM selenium/standalone-firefox:4.0.0-beta-3-prerelease-20210422

#==============================
# Sauce Labs logo as wallpaper for Fluxbox
#==============================
COPY saucelabs_logo_red_bolt.png /usr/share/images/fluxbox/ubuntu-light.png
