#== FROM instructions support variables that are declared by
# any ARG instructions that occur before the first FROM
# ref: https://docs.docker.com/engine/reference/builder/#understand-how-arg-and-from-interact
#
# To overwrite the build args use:
#  docker build ... --build-arg SELENIUM_TAG=4.0.0-beta-3-20210426
ARG SELENIUM_TAG=4.0.0-beta-3-20210426
FROM selenium/standalone-docker:${SELENIUM_TAG}

COPY selenium-server.jar /opt/selenium/selenium-server.jar
