name: Build & test

on:
  push:
  pull_request:
    branches:
      - trunk

jobs:
  build-and-test:
    name: Build & test Sauce To Go Docker images
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Output Docker info
        run: docker info
      - name: Build jars
        run: |
          docker run --rm -ti \
          -v ${PWD}:/usr/src/mymaven \
          -v ${PWD}/.m2:/root/.m2 \
          -w /usr/src/mymaven \
          maven:3.6.3-jdk-8 mvn clean package
