name: Build & test

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build & test Sauce To Go Docker images
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Build jars
        uses: ./.github/actions/build-jars
      - name: Build Docker images
        uses: ./.github/actions/build-docker-images
