name: Build & test

on:
  push:
  pull_request:
    branches:
      - trunk

jobs:
  build-and-test:
    name: Build & test Sauce To Go Docker images
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Output Docker info
        run: docker info
      - name: Build jars
        run: |
          docker run --rm \
          -v ${PWD}:/usr/src/mymaven \
          -v ${PWD}/.m2:/root/.m2 \
          -w /usr/src/mymaven \
          maven:3.6.3-jdk-8 mvn clean package
      - name: Get jars version
        run: |
          echo "JAR_VERSION=$(docker run --rm \
          -v ${PWD}:/usr/src/mymaven \
          -v ${PWD}/.m2:/root/.m2 \
          -w /usr/src/mymaven \
          maven:3.6.3-jdk-8 ${MVN_COMMAND})" >> $GITHUB_ENV
        env:
          MVN_COMMAND: "mvn org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate"
      - name: Output jars version
        run: echo ${JAR_VERSION}
      - name: Moving jars to docker directory
        run: |
          mv sauce-grid/target/sauce-grid-${JAR_VERSION}-jar-with-dependencies.jar docker/selenium-server.jar
          mv sauce-assets-uploader/target/sauce-assets-uploader-${JAR_VERSION}-jar-with-dependencies.jar docker/sauce-assets-uploader-${JAR_VERSION}.jar
      - name: List docker directory
        run: ls docker
      - name: Build docker images
        run: cd docker && make all && cd ..
