name: Push Docker images

on:
  push:
    branches:
      - trunk

jobs:
  push-images:
    if: contains(toJson(github.event.commits), '[push]') == true
    name: Build & push Sauce To Go Docker images to Docker Hub
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Build jars
        uses: ./.github/actions/build-jars
      - name: Build Docker images
        uses: ./.github/actions/build-docker-images
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push images to Docker Hub
        run: cd docker && ./push_images.sh
